# Evidence Gate Configuration
# This file controls how the Evidence Gate action behaves in your workflow

# Action mode: warn | fail | enforce
mode: warn

# Whether to require SBOM files (default: true)
require_sbom: true

# Whether to require provenance attestations (default: false)
require_provenance: false

# Paths to search for SBOM files
sbom_paths:
  - sbom.cdx.json
  - sbom.spdx.json
